/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#1c1b1b",
        "on-background": "#1a1c1b",
        "secondary": "#934b19",
        "surface-tint": "#5e5e5e",
        "tertiary-fixed": "#e5e2e1",
        "primary-fixed": "#e2e2e2",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#c8c6c5",
        "on-secondary-container": "#783603",
        "on-secondary-fixed": "#321200",
        "primary": "#000000",
        "surface-container-high": "#e9e8e6",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#c6c6c6",
        "inverse-primary": "#c6c6c6",
        "on-error": "#ffffff",
        "outline-variant": "#cfc4c5",
        "background": "#faf9f7",
        "surface-variant": "#e3e2e0",
        "on-primary-fixed": "#1b1b1b",
        "outline": "#7e7576",
        "inverse-surface": "#2f3130",
        "tertiary": "#000000",
        "on-surface": "#1a1c1b",
        "on-secondary": "#ffffff",
        "tertiary-container": "#1c1b1b",
        "error-container": "#ffdad6",
        "surface-bright": "#faf9f7",
        "on-primary-container": "#848484",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#ffdbc9",
        "surface-container-low": "#f4f3f1",
        "on-secondary-fixed-variant": "#753401",
        "on-tertiary-fixed-variant": "#474746",
        "surface-dim": "#dadad8",
        "on-tertiary-container": "#858383",
        "on-error-container": "#93000a",
        "surface-container": "#efeeec",
        "on-surface-variant": "#4c4546",
        "inverse-on-surface": "#f1f1ef",
        "on-primary-fixed-variant": "#474747",
        "secondary-container": "#ffa26a",
        "primary-container": "#1b1b1b",
        "surface": "#faf9f7",
        "surface-container-highest": "#e3e2e0",
        "secondary-fixed-dim": "#ffb68c",
        "error": "#ba1a1a",
      },
      fontFamily: {
        "display": ["Playfair Display", "serif"],
        "sans": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-md": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "1.2", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "button-text": ["14px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      spacing: {
        "container-max": "1440px",
        "section-gap": "120px",
        "section-gap-sm": "64px",
        "margin-edge": "40px",
        "gutter": "24px",
      },
      borderRadius: {
        DEFAULT: "0px",
        sm: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        full: "9999px",
      },
      maxWidth: {
        "container": "1440px",
      },
      boxShadow: {
        lux: "0px 20px 50px rgba(0, 0, 0, 0.04)",
        "lux-md": "0px 8px 24px rgba(0, 0, 0, 0.06)",
      },
    },
  },
  plugins: [],
}
